<!DOCTYPE html>          
<html>       
  <head>
		<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
		<meta  charset="UTF-8">

		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?> /css/fruitBazaar.css"/>
		<link href="<?php echo $this->baseUrl(); ?> /css/main.css" rel="stylesheet" type="text/css" />
		<link href="<?php echo $this->baseUrl(); ?> /css/nav.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/script/script.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/script/modernizr.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/script/utils.js"></script>
	    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/script/jquery.js"></script>
	</head>

	<body width="100%">
		
		<?php echo $this->layout()->content ?>
	</body>
</html>
